### ISSUE TITLE
Password protected private conversations are easily accessed

### ISSUE THREAD

**Issue by funkyeah** [klinker-apps/pulse-sms-issues#1000]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.
- [x] This is not a general support question.

## Device/Platform Information

**Device with issue: Samsung Galaxy S8, Android Ver 9 **
**App version: v5.3.0.2738 **

## Describe the Bug

My password protected private conversations can be easily accessed by simply opening the default me Messages application. All password protected conversations show up in that application without even making it the default SMS app again.

### Steps to Reproduce

1. Install Pulse
2. Open and make it the default SMS application
3. Create new conversation
4. Make it private and password protect it
5. Send additional password protected messages
6. Go back to original SMS app
7. In my case hit cancel when the app asks "Pulse is currently your default messaging app. Do you want to make Messages your default messaging app"
8. Observe recently sent password protected private messages are freely viewable without entering a password

### Expected Behavior

I would expect the password protected messages on not viewable in any other SMS app.

### Screenshots

I think the explanation is clear enough and screenshots would not provide any additional insight but requested I can provide them.

### Additional Information

This was confirmed by another person using a similarly configured S8.

**Comment by klinker24** [comment]
Sorry, this is not something that is planned to change. Other messaging apps might handle this differently, but Pulse will protect your messages within my app alone. I do not feel as though it is right to manage access to SMS messages in other applications.

Most devices will allow you to disable the stock messaging app.

**Comment by funkyeah** [comment]
I understand SMS is somewhat inherently insecure but I was still totally surprised by this behavior. I imagine it would be fair to say that less technical users would also be very surprised that password protected Pulse conversations can easily be accessed without a password by installing another SMS application.

I can see the arguments for why this feature can't or shouldn't be implemented but making this behavior/vulnerability clear to users seems like a reasonable request.
