### ISSUE TITLE
Ability to use regex in blacklist phrase

### ISSUE THREAD

**Issue by WereGoingOcean** [klinker-apps/pulse-sms-issues#1001]
## Confirm this Issue

- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.
(It is mentioned in the blacklist FAQ that they do not currently support regex by design).
- [X] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Describe Your Request

An option to allow regex usage in the blacklist phrase (possibly toggled on / off?).

I constantly get spam texts like the following:
`50lbs60Days: Free to try: (url) Stop to Stop`
`Today'sFreeHoroscopeReading: See what's in store for May 31, 2020. (url) Stop to Stop`

It would be nice if in the blacklist phrase section it was possible to hit a checkbox to enable regex support. Then I could enter a regex that'd filter all these different spam texts out.

The blacklist FAQ mentions they are not regex supported by design. Would it be possible to add a checkbox to enable regex on certain blacklist phrases? Possibly behind a warning or something to make sure they know what they're doing.

### Describe alternatives you've considered

I can blacklist a phrase or part of the url from individual texts but new ones for different sites always show up.

**Comment by klinker24** [comment]
This is not something that I plan to add into the main app, sorry. To me, that is just way to dangerous and there are too many people that wouldn't have a clue what this is. Pulse isn't meant as a developer tool, it is a consumer tool.

If this is really something you wanted, this is the type of thing that the open source experiments section of settings would be great for. I discuss contributions to this section on the project's readme: https://github.com/klinker-apps/pulse-sms-android#contributing-to-pulse

This is not something that I plan to code into the main app though, sorry. This wouldn't be difficult to add, it just isn't something I am going to add or maintain.
