### ISSUE TITLE
Pulse not updating conversation/contact names

### ISSUE THREAD

**Issue by Hoodlook** [klinker-apps/pulse-sms-issues#1004]
This is a problem that I have dealt with consistently. 

When adding new contacts Pulse does not refresh conversations with their updated contact names. 

For example if I'm in a group chat and I save these unknown numbers as "idk1", "idk2", "idk3" etc, and then I text these people to ask for their names and then once they reply back I rename the contacts to the correct names, the conversations still say "idk1", "idk2", "idk3" etc. 

Force stopping the app and restarting it or restarting the phone does not fix the issue. The only way to fix it is by a clearing all of the app's data which requires it to reoptimize(not exactly a quick process) upon relaunching.

**Comment by klinker24** [comment]
You can go to any conversation's settings menu and update the conversation title via the top option.

If the title is currently a phone number and you open the conversation, it will update it with the contacts name in your contacts app (if you have assigned them a name.)

If the conversation title is already a name, you will need to update it manually. This is not planned to change. You do not have to clear the app data.
