### ISSUE TITLE
Specific message reply

### ISSUE THREAD

**Issue by ifortworth** [klinker-apps/pulse-sms-issues#1006]
## Confirm this Issue

- [x ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [x ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.
- [x ] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Describe Your Request

I would like to see a feature implemented that allows for the reply to a specific message sent. Much like FB Messenger and other apps are going to. 

### Describe alternatives you've considered

N/A

**Comment by klinker24** [comment]
That is not something that SMS will ever be able to support, unfortunately. That just isn't how the protocol works.

**Comment by ifortworth** [comment]
Thanks for the reply...
