### ISSUE TITLE
Feature Request: Ability to Blacklist Mobile Numbers based on Keywords

### ISSUE THREAD

**Issue by 8227846265** [klinker-apps/pulse-sms-issues#1007]
Hello, I keep receiving spam SMS from different numbers. No matter how many numbers I blacklisted, they will send me a new SMS from a new number. However, the pattern on their SMS is that they will always include their business name.

Is it possible to blacklist based on keywords? I'm getting annoyed with their persistence in sending unsolicited spam SMS that can't be unsubscribed.

**Comment by klinker24** [comment]
It seems extremely risky to add a feature to blacklist by a sub-portion of a phone number. Users could easily misunderstand that.

Why not just use the "blacklist by phrase" option that is already there? If their messages always contain the business name, just blacklist the business name.

**Comment by 8227846265** [comment]
Sadly, there's no business name on the number. The spam SMS I receive are all disposable phone numbers.

What I meant about their business name is in the SMS Content.

Sample of their SMS
- Get a trip to X country for X amount — Travel Tour Inc.

Regardless of what number they use. It will always have Travel Tour Inc.

Like this.

**Comment by klinker24** [comment]
That is exactly what I am talking about. Just blacklist that phrase. Don't worry about the phone number at all. 

Pulse has always allowed you to blacklist by phone number, or by phrase.

**Comment by 8227846265** [comment]
I tried checking the settings but I can't seem to find it. I'm on Android.

**Comment by 8227846265** [comment]
Found the ability to blacklist phrase. Had to go to Blacklist Conversation > Click + > then Enter Phrase
