### ISSUE TITLE
Link preview doesn't work on many links

### ISSUE THREAD

**Issue by Apexogenesis** [klinker-apps/pulse-sms-issues#1008]
## Confirm this Issue

- [##] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [## ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [ ##] I have verified that this is something that is reproducible.
- [## ] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Device/Platform Information

**Device with issue:** Android phone with Android 10
**Primary device:** Ex: Xiaomi Mi 9T pro
**App version:** Ex: 5.4.0.2761

## Describe the Bug

Some web sites or links suck as www.forbes.com or articles from Forbes do not produce link previews, link previews are very hit and miss. 
Also

I know you don't like link previews on outgoing messages but they are important when scrolling back through old text or searching old text. Please consider adding this

### Steps to Reproduce

1. Go to text app
2. Copy a text link to send to yourself or have a friend send you a link from Forbes.com
3. No link preview is shown

### Expected Behavior

See a link preview

### Additional Information

Add any other context about the problem here. Device configuration, unique cases, anything that you think may be relevant.

**Comment by klinker24** [comment]
The app previews outgoing messages the same as incoming ones. 

Previews are generated if the in-app browser is able to display the content. If you would like, you can open an issue on that project for generating previews on forbes links: https://github.com/klinker41/article-android
