### ISSUE TITLE
Providing Linux desktop application as flatpak package on FlatHub

### ISSUE THREAD

**Issue by Nokia808** [klinker-apps/pulse-sms-issues#1009]
I would like to suggest to make the Linux desktop application available as flatpak package on FlatHub.

Flatpak is a universal Linux package which is more secure & convenient than AppImage. It is sandbox by default & automatically updated. If you make your application available as FlatHub, then it will be available for almost all Linux distros & users .... 

1. home page of FlatHub is:
    https://www.flathub.org/home
2. FlatHub repositories are at:
    https://github.com/flathub
3. when some one like to add package to FlatHub, she/he need to open PR at:
    https://github.com/flathub/flathub/pulls
4. FlatHub differ from snap by being allow any one to package not only developers of packages. So packages on FlatHub are of 2 kinds regarding this point: some are packaged by their developers like RetroShare, while other are packaged by person other than their developers. So,
5. developers of Pulse SMS themselves can package their Linux desktop application by themselves. This will be ideal.
6. all packages on FlatHub are signed .....
7. even if person other than the original developer(s) maintain the package on FlatHub, FlatHub team try as much as possible to make developer(s) authorized to repositories at least to monitor & follow up the packaging ......
8. FlatHub allow both open & closed source packages. But regarding open source packages, the FlatHub team insisting on packager to make them deterministic (reproducible).

We wish to see your great application available on FlatHub in near feature.

**Comment by probonopd** [comment]
As for AppImage,

- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others) - without you having to install anything else first (like a Flatpak runtime etc.)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter
- No repositories needed. Suitable/optimized for air-gapped (offline) machines
- Decentralized

**Comment by Nokia808** [comment]
@probonopd 

Hi. Fortunately, I was asking other developer same request & he replay same of your replay (favour AppImage) but I replay him & he tried by himself then changed his mind (rejecting AppImage for it's difficulties). Kindly, see the following bellow link & read it carefully & look how the developer changed his mind. My user name on sourceforg is "nokia808":
https://sourceforge.net/p/xmedcon/feature-requests/19/

Bellow I will re-post my replay on that developer, because it is valid here, also:

"1) AppImage format will cost you more efforts than flatpak, because you need to give indevidual built-in support for every distro you like your AppImage to run on - within same AppImage universal package that you will create. There is no such additional efforts with flatpak - see:
https://github.com/junrrein/pdfslicer/issues/103

2) AppImage need to be manually installed. Manuall instalation is not a convenent method for Linux & AppImage is only usable on Linux. It should not be used unless as last option when all other options fail or if the targeted application is pure portable package ...

3) AppImage is volnarable to man in middle attackes - again due to manuall download & installation.
To overcome this problem you need to sign your AppImage by OpenPGP key. To me I know how to use OpenPGP to verify package but there are many peoples not know this.
As alternative to OpenPGP, you should post SHA512 checksum hash. But it is not ideal for protection & - again - many users not know how to use it or simple not know that it is posted within yml file that posted by developer on the repository.

4) AppImage has no built-in integration with DE of Linux. It need the user to create launcher icon for it manully, a process I know how to do but for many users it is difficult ... Even if user know how to do this, it remain not convenent .....

5) Most AppImage has no built-in automatic update mechanism. This make user in need to re-download & install every new release - again a not convenent method ...
There is already a method to implememt built-in update mechanism for AppImage, but most AppImage that use to implement it are not working perfectly so that users need for manual download & re-installation from time to time on occusions ! The only exception for that is jitsi-meet-electron - see:
https://github.com/jitsi/jitsi-meet-electron
jitsi-meet-electron is the only AppImage that support automatic updates without problems at all. I tried so many AppImages & did not see any one like jitsi-meet-electron.

Kindly, please reconsider your choice."

Only one additional comment I will add here:
You said the following " ....... without you having to install anything else first (like a Flatpak runtime etc.)"
This is for make your packaging of flatpak easier by sharing part of the work on behalf of Flatpak team (I mean run time ---- etc), so that your work in creating & maintaining your flatpak will be much less painful.

**Comment by probonopd** [comment]
There is no right or wrong. That developer seems to have other priorities. Me - I don't like to install anything. Just download one file and run it. He - seems to like package managers. We both have our points. There is no "one size fits all" solution.

**Comment by klinker24** [comment]
Sorry for the late reply. At this time, I do not plan to officially support any additional packaging types for the desktop app. It is open source though. You should feel free to build the app into whatever type of package you need

https://github.com/klinker-apps/pulse-sms-desktop
