### ISSUE TITLE
Allow adding numbers from contact list & call/message log to the blacklist.

### ISSUE THREAD

**Issue by Nokia808** [klinker-apps/pulse-sms-issues#1010]
*Please read my notes, then replace my notes to fill in this template with your own information and check the boxes to confirm you understand the request.*

## Confirm this Issue

- [\ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [\ ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.
- [\ ] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Describe Your Request

Currently, if user like to add number(s) to blacklist of application, she/he need to enter it manually by enter it's digits one by one ! This is, currently, the only way !

### Describe alternatives you've considered
The users should have other 2 options (BESIDE the current one). These are:
- select from "contacts list",
- select from message/call log

### Additional information
The option to [select from "contacts list"] is more important than [select from call/message log] option.

**Comment by klinker24** [comment]
I cannot integrate with your call log or contacts apps. They are not my apps, so I cannot affect the way it works. You would have to copy and paste the number from your contacts app or call log, if that is what you need to do. The blacklist section will support pasting the number just fine. You don't have to input it manually.

If the person actually sent you a message, simply open the conversation. There is a "blacklist" option in the three dot overflow menu, in the top right corner. This has always existed. I appears that that is what you are looking for.

**Comment by Nokia808** [comment]
@klinker24 
I see. Thank you for explanation !
