### ISSUE TITLE
Add "White List" option

### ISSUE THREAD

**Issue by Nokia808** [klinker-apps/pulse-sms-issues#1014]
*Please read my notes, then replace my notes to fill in this template with your own information and check the boxes to confirm you understand the request.*

## Confirm this Issue

- [ \ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [ \ ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.
- [ \ ] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Describe Your Request

Add "White List" option

### Describe alternatives you've considered

This feature useful when user need to use "Receiving message from ono-contact" at "Immediately discard the message as spam", but there is a message came from sender but have no number to be added !!
Let me explain: I installed your application to utilize "Immediately discard the message as spam" feature (because my Nokia 7.2 mobile has no such feature at this time), but there is a sender send me notification messages that not linked with a number - it has only a head title refer to name of company ! What I tried to get number for it, ended by failure ! On my previous HONOR mobile, I was able to overcome this by adding this message to "White List" option so that it was excluded from already activated "Block messages from number not in contacts .....

**Comment by klinker24** [comment]
Sorry, at this time, a whitelist is not planned for that feature. This would directly conflict with the blacklist that Pulse already has and just generally cause confusion.

**Comment by Nokia808** [comment]
@klinker24 
Hi dear cute developer ! I discover that there is no need for "white list" to solve my case, because your application has other feature that NOT EXIST in default SMS program of my mobile. This feature is "View contact". Using this option "View contact", I succeeded in adding the message sender (who has no any digits number) to my address book. Then after, I activate "Immediately discard the message as spam" & that is all !

Really, your applications has options not available in other SMS applications !
