### ISSUE TITLE
edit photo menu doesnt work

### ISSUE THREAD

**Issue by cdeitrich00** [klinker-apps/pulse-sms-issues#1016]
Edit photo menu force closes when i click on the edit icon circled in the screenshot. Running on samsung note  10 plus

![Screenshot_20200802-113949_Pulse](https://user-images.githubusercontent.com/56947221/89126617-ff42ef80-d4b4-11ea-9ed8-5ace537046cb.jpg)

**Comment by klinker24** [comment]
If you can provide a log, that would the best way to get it fixed. I am not seeing ant crash reports on the Play store related to this, nor have I heard this feedback before, so I am not sure how to debug this.

**Comment by R0tten** [comment]
On OnePlus 6 running pi, I am not able to replicate this :(

**Comment by sbmorris** [comment]
I too have this issue.

**Comment by R0tten** [comment]
> I too have this issue.

Have you cleared the cache and data then tried again?

**Comment by klinker24** [comment]
I made a change around the in-app editor. I am still unable to replicate this issue, so I do not know if it will fix or help anything, but please let me know either way.

**Comment by klinker24** [comment]
I am going to close this as resolved, since I have not heard back. Let me know otherwise.
