### ISSUE TITLE
Adding options like bold and italic to words

### ISSUE THREAD

**Issue by Gabe-but** [klinker-apps/pulse-sms-issues#1018]
Adding a feature where you can click and hold on a typed out phrase and an option to bold and italic the words will appear beside the clipboard and past options(like in WhatsApp)

This would be a good addition to the app so that when people text they can use these options to add importance to certain words or to make certain words more obvious in a paragraph(like dates and times).
Adding this feature makes it so that the person sending the text doesn't have to go to Google and use a convertor to convert words from one style to another.

**Comment by klinker24** [comment]
Different styles simply will not show on SMS messages though... You can't go to Google and convert between different styles. That just isn't something that SMS supports, SMS is just plain text, no meta-data. 

This isn't going to be possible for an SMS app.
