### ISSUE TITLE
Adding a like feature to SMS

### ISSUE THREAD

**Issue by Gabe-but** [klinker-apps/pulse-sms-issues#1019]
When someone likes your text on iMessage you receive a text saying 'Liked:and then the message they liked'. This basically implies that when liking a text, the app the person is texting me on automatically sends a text to me saying that the person I'm texting liked my message. I would love the option to like a text from the person I'm texting and have the app simply send the person a text saying 'Liked:and the text I liked'. The reason I would want the app to send a text is because it's SMS and that's the only way it could work without the chat being MMS.

**Comment by klinker24** [comment]
Similar response as to #1018. This just isn't possible for SMS apps. SMS does not support meta-data, it is a plain text format for everything

**Comment by klinker24** [comment]
You could send the same message back to imessage users and it would appear as a "like" for them. Android SMS is just handled completely different from imessage or other internet messaging protocols

**Comment by Gabe-but** [comment]
Yeah I meant just have a plain measage sent saying liked.
I'm aware that iMessage and Android don't play very well together and it's pretty disappointing in my opinion.

**Comment by klinker24** [comment]
Sorry, but that isn't something that is planned for the app. That just isn't a very good feature and would be extremely confusing for most people since they would not understand the distinction between imessage and SMS.
