### ISSUE TITLE
Feature request: reorganize app layout for tablet

### ISSUE THREAD

**Issue by bjs03** [klinker-apps/pulse-sms-issues#1020]
Describe your request:
I really like using Pulse SMS on all of my devices. However, on my new Galaxy Tab A with S-Pen (SM-P200) that I got last december, the Pulse UI is ok, but I think the UI could be improved to make the tab experience better. 

I think there should be an option for the current UI layout as well as a new option described below. In the new UI, I suggest moving the list of contacts that someone messages to the left, where the menu bar is. The menu bar could then be drawn out with a button on the left. On the right, where the list of contacts with messages is right now, the conversation can be displayed. This way, people can take maximum advantage of the screen real estate. 

Describe alternatives you've considered:
Not sure.

Additional information:
When the menu bar is drawn out, it should not cover the message part of the app.

**Comment by klinker24** [comment]
At this time, changes to the tablet layout are not planned. To be honest, the tablet app just doesn't have enough users. The vast majority of people just use Pulse on their desktop. 

If this is something that changes in the future, I will definitely look into re-opening this issue. 

If this is something you need right now... The app is open source, this change could be made, it just cannot be a priority for my development, at this time: https://github.com/klinker-apps/pulse-sms-android
