### ISSUE TITLE
Contact changes don't sync with app or web app.

### ISSUE THREAD

**Issue by ted1735** [klinker-apps/pulse-sms-issues#1023]
This had been the single biggest turnoff for this app! I love everything about pulse SMS, functions, delay future send, web access, chrome app, Samsung watch app! etc. The contacts not updating seems like a real BIG miss. Every other SMS app I have used updates this correctly...why can't pulse do it. And why doesn't when I use the web version, it properly sync my contacts.... These issues have been reported and reproducible I just would like them fixed. This would be a works class app!

_Originally posted by @ted1735 in https://github.com/klinker-apps/pulse-sms-issues/issues/1017#issuecomment-683429472_

**Comment by klinker24** [comment]
Sorry, I do not update conversation information automatically. This is not planned, as I said in the referenced issue.
