### ISSUE TITLE
Spam inbox / unknown number filter

### ISSUE THREAD

**Issue by tgjohnst** [klinker-apps/pulse-sms-issues#1024]
## Confirm this Issue

- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.
- [x] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Describe Your Request

These days, I receive multiple spam texts a day, all of which are sent from different random numbers. Blacklisting and/or reporting (as in #1013) a specific number does nothing to stop future texts. Wholesale blocking unknown numbers (which is possible on some phones) precludes the receipt of e.g. 2FA codes or app-related texts, so that is not a solution either.

It would be helpful to have a feature that filters texts from unknown/unrecognized numbers into a specific 'potential spam' folder or location so that they do not clutter the inbox, but could still be checked if a text is expected. A bonus feature on top of this would be to turn off notifications for any texts that are filtered that way.

### Describe alternatives you've considered

A less functional but possibly easier to implement alternative would be a setting toggle to auto-mute all conversations arriving from unknown numbers, so at least there would be no notifications.

**Comment by klinker24** [comment]
There is already an option to turn off notifications for conversations coming from unknown numbers. Head to settings -> "Advanced features". That same preference also allows you to ignore those messages and discard them immediately, as if they were blacklisted.

At this time, any messages matching your blacklist or hit by this filter are immediately discarded. There are no plans to set up a "spam inbox" with Pulse, though.
