### ISSUE TITLE
Whitelist numbers, area codes.

### ISSUE THREAD

**Issue by kalav** [klinker-apps/pulse-sms-issues#1026]
*Please read my notes, then replace my notes to fill in this template with your own information and check the boxes to confirm you understand the request.*X
## Confirm this Issue

- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.
- [X] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Describe Your Request

Spam text messages seem to outnumber my legitimate messages. Blacklisting is good for blocking specific numbers, but at the rate they're coming in, I'll be here blocking till the cows come home.

On the other hand, I do know who or from which area codes I want to accept messages from, so for me, whitelisting these would be a good thing. And of course (maybe) blacklisting would trump whitelisting.

### Describe alternatives you've considered

Have considered blacklisting text that may be common in spam messages, but that's too hit-or-miss, and it may block messages I'd like to see.

**Comment by klinker24** [comment]
I do not feel as though a whitelist based on area code is the best way to manage spam. You would be unable to receive messages from anyone new, effectively. People can keep their old phone numbers across different area codes, so there is no guarantee that even the people living right down the street from you have the same area code for their phone number. I guess I fail to see how this would be safer than blacklisting by phrase. 

I really am against adding a whitelist on top of the current blacklist... I don't think that the app should have both. That would be confusing to the majority of users. 

Pulse does have tools to manage messages from unknown numbers. You can set up the app to immediately discard the messages as if they were blacklisted, mute those conversations, or just receive them as normal. Honestly, I think that this is as far as I am comfortable going. I do not think that a whitelist by area code would be more effective than the tools that Pulse already provides
