### ISSUE TITLE
Cant send SMS or MMS over airplane WiFi

### ISSUE THREAD

**Issue by joebob692** [klinker-apps/pulse-sms-issues#1030]
*Please read my notes, then replace my notes to fill in this template with your own information and check the boxes to confirm you understand the report that you are filing.*

## Confirm this Issue

- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.
- [x] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Device/Platform Information

**Device with issue:** Galaxy S9 SM-G960U/Microsoft Surface Pro/Dell XPS 15
**Primary device:** Galaxy S9 SM-G960U Android V10
**App version:** 5.4.5.2802

## Describe the Bug

When connected to airline WiFi, SMS and MMS will not send. I have tried it on Southwest, United, and Delta. Wifi calling is enabled on the phone and I can send messages through the stock SMS app.

### Steps to Reproduce

1) Get on a plane
2) Connect to WiFi
3) Try to send SMS or MMS

### Expected Behavior

It gets stuck on sending then fails after a few minutes.

**Comment by klinker24** [comment]
Unfortunately this isn't something that a third party app can control. All that I am able to do is hand off messages to Android to be sent. I do not get to control the sending process and will not be able to affect your ability to send or receive over wifi connections.
