### ISSUE TITLE
Sync global settings 

### ISSUE THREAD

**Issue by Skullmonkey** [klinker-apps/pulse-sms-issues#498]
**Device with issue:** Pixel XL Android 8.1
**Primary device:** Pixel XL Android 8.1
**App version:** 2.6.0.1695

**Additional information:**
Currently, from what I can tell, global settings do not get synced when logging in to a device, it seems to always go back to default settings. Would it be possible to sync the global settings to the cloud so that they get restored when logging in to a device.

The only problem I could see with doing this is people use more than one mobile device (such as a phone and tablet) that would want different settings for each device. A possible solution would be to either set device specific settings based on model or allow the users to set up 'profiles' that can be selectable upon logging in.

**Comment by klinker24** [comment]
Some of the settings are synced, specifically the theme settings. In the future, maybe I will sync more of them. I don't see any problems doing it this way or a need for profiles on this. If I get in to this, then all of the settings will sync.

**Comment by myspivey** [comment]
Sync of the settings between desktop and Android also seems to be spotty. Currently on the latest from both and the desktop only shows my selected theme of dark very occasionally. I have tried the advice of switching settings on the phone to force an update and this does not seem to impact the desktop client ever.

**Comment by klinker24** [comment]
Settings are not automatically applied to the web. You need to press the top preference on the web's settings page to apply them. 

Seems to me like you haven't applied the settings and your web app is using the day/night theme.

**Comment by myspivey** [comment]
I see, that did seem to be the problem. IMO that is not intuitive. Thanks for the information.

**Comment by klinker24** [comment]
I do it this way so that the web app is not forced to have the same settings as the Android app. Not everyone would like a dark theme on the web, while they may like it on a phone screen. That top preference does say that you need to click it to pull in the settings.

**Comment by mazimmer** [comment]
> Settings are not automatically applied to the web. You need to press the top preference on the web's settings page to apply them.
> 
> Seems to me like you haven't applied the settings and your web app is using the day/night theme.

Would it be possible then to only show the "reload" button only on the settings screen? I've always thought it's "resync with server", and I would press it to get SMS that were on my device but not yet on the desktop...

Also, it would help to label that button "sync settings", IMHO.

**Comment by klinker24** [comment]
I think I am going to close this one. Currently, all of the theme related settings are transferred, as well as any per-conversation settings. That is as far as I am going to go. 

The web app also downloads settings automatically now, and has for quite awhile.
