### ISSUE TITLE
Bulk actions on conversations

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/pulse-sms-issues#718]
**Feature Request:**

On Android, we can long click any conversation to start the multi-select process. From there, we can do bulk actions (archive, delete, mark as unread).

I would like to bring this to the web app. Since the web doesn't have any type of long click ability, I will enable the multi-select by clicking on the contact avatars. This will change the app bar to a dark color, and change the icons that are shown on it.

**Additional information:**

When in the multi-select mode, clicking any conversation should highlight it. The user shouldn't have to click just the thumbnail image.

**Comment by ems170** [comment]
Please add the bulk forward option as well. It's very useful when forwarding multiple received image or other media type files.

**Comment by are-dev** [comment]
I'm unable to select multiple messages & delete. If this feature is available in the web app, how to enable it?

**Comment by klinker24** [comment]
This issue is still open, because it hasn't been implemented yet.

**Comment by are-dev** [comment]
By when can we expect to have this very important feature?
