### ISSUE TITLE
Do not trust desktop time for web interface

### ISSUE THREAD

**Issue by ryan77627** [klinker-apps/pulse-sms-issues#791]
For a while I was wonder why messages I send were appearing over messages I already got on my phone. I finally figured out my desktop was 5 minutes slow, and the web app was using it's time. Would it be practical to implement a quick time check into the web app since it can be assumed the user has internet connectivity?

**Comment by klinker24** [comment]
It wouldn't be practical, but it could be possible to implement something around this. Thanks for the request. The timestamp being off is also noted on my help page.

https://messenger.klinkerapps.com/help

**Comment by klinker24** [comment]
I made changes around this some time ago. This is the most that I feel comfortable doing, right now. There are comments in the code about how the situation is handled:

https://github.com/klinker-apps/pulse-sms-android/blob/master/shared/src/main/java/xyz/klinker/messenger/shared/service/FirebaseHandlerService.kt#L273
