### ISSUE TITLE
Galaxy Watch 46mm LTE

### ISSUE THREAD

**Issue by js202137** [klinker-apps/pulse-sms-issues#895]
Easiest way to explain is when I have the watch in full LTE mode, no phone around or connected through Bluetooth. If I try to open the Pulse app the screen stays white with the loading circle going around and around. It will not open the app until I'm back in vicinity of my phone and reconnected to Bluetooth.

**Comment by klinker24** [comment]
Hmm, Pulse doesn't know or care what type of connection you have. It just makes the data call and the watch returns the results. I feel like this is something on the system side? At least I don't know of a way to change the behavior or tell the watch that it should work with or without a Bluetooth connection

**Comment by js202137** [comment]
Any idea what on the system side would need to be changed? I’ve tried toggling pulse notifications on and off, rebooting the watching, uninstalling and reinstalling the app on both sides. Testing right now The texts are going to the watch, notifications are going off and I can view in the default messages app on the watch but pulse just spins when I open.

**Comment by klinker24** [comment]
I am not really sure, sorry. I have been looking through Samsung's documentation and I am not seeing anything at all about this issue or any direction on how to solve it.

**Comment by madthumbz** [comment]
I'm having the same issue as described above. I have a lg g8 phone and samsung galaxy 46 mm watch it only works Bluetooth. I like the app alot but with this issue I dont want to purchase a half working product. Ive tried everything described above and more.

**Comment by js202137** [comment]
I guess good to hear someone else is having this issue too, so it's not isolated to just me. Currently running in full LTE standalone mode and cannot access the pulse app, messages coming through the Galaxy messages app.


Sent from Pixel

**Comment by ieitsme** [comment]
Same issue here, I think it's because the phone and watch have different sim and different phone numbers. If there were a way to forward to my lte watch number that would be nice.

**Comment by klinker24** [comment]
Sorry all, I am going to close this one. I just have not found anything related to it on Samsung's documentation, nor do I have any further insight. If someone else finds a reference to this issue, an explanation, or a workaround, I would be happy to re-open it.
