### ISSUE TITLE
Saving multimedia (pictures) with contact name in filename

### ISSUE THREAD

**Issue by mattehicks** [klinker-apps/pulse-sms-issues#912]
I have used this app for a few years now. Its a great app.

I would love to see this feature implemented, as any saved picture messages quickly become untrackable when downloaded.
Can they perhaps have a contact name and date as the filename?
Specifically referring to Andoid and Desktop app.  Desktop app is a priority as all images are saved and overwritten as "pulse-image.jpg"  (very annoying)
Thanks!

**Comment by klinker24** [comment]
I can make it unique pretty easily, but adding the contact name to the filename is less trivial. I will make it unique for now, and add this to the backlog for the future.

**Comment by klinker24** [comment]
I think that I am going to stick with just having the unique names, sorry. There is a lot of additional overhead for communicating the contact name between the different services and I think that just having the unique file names does effectively the same thing.
