### ISSUE TITLE
Double Simcard : messages sent with the wrong simcard

### ISSUE THREAD

**Issue by nandrewlive** [klinker-apps/pulse-sms-issues#937]
**Device with issue:** Honor view 10 BKL-L09
**Primary device:** Android 9
**App version:** 4.13.3.2637

**Describe the bug:**
If I change the simcard when sending a message (sim 1 or sim 2) it doesn't send the message with the right sim (often with the default sim) 

**Steps to reproduce:**

1. Go to a contact an send a message with sim1 and then sim 2
2. The receiver receive two message from sim 2

**Comment by klinker24** [comment]
Sorry, I really have no idea why that would be. Dual SIM support is managed completely through Android and I have not heard from others on issues around this. 

I really just tell Android "here is the message I want to send and here is the SIM subscription ID that the user selected".

I can explore your report further, but I am not sure where I will be able to get with it. I cannot replicate your issue through the steps you have provided, on any of my dual SIM devices.

**Comment by nandrewlive** [comment]
Thank you for your kind answer!

Le mar. 5 nov. 2019 à 21:39, Luke Klinker <notifications@github.com> a
écrit :

**Comment by klinker24** [comment]
I am going to close this. I am not able to replicate this issue, nor do I have much control over which SIM messages get sent on. All of that is handled on Android's side.
