### ISSUE TITLE
Support Linux distribution through Flatpak

### ISSUE THREAD

**Issue by tristan957** [klinker-apps/pulse-sms-issues#947]
## Confirm this Issue

- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.
- [x] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Describe Your Request

On Linux, Flatpak has gained substantial momentum for third-party apps to use for distribution. It would really be helpful for Linux users who don't run a Debian-based or RPM-based distro to install. Other benefits of Flatpak are the containerization characteristics it brings to the table.

### Describe alternatives you've considered

Another alternative in Snap packaging, but Flatpak is a little bit better supported across different distributions at the moment. AppImage is definitely not the goto third-party distribution tool anymore.

### Additional information

https://www.flathub.org/home
https://snapcraft.io/

**Comment by klinker24** [comment]
Unfortunately, Electron builder does not support flatpak

https://www.electron.build/configuration/linux#LinuxConfiguration-target
https://github.com/electron-userland/electron-builder/issues/512

**Comment by tristan957** [comment]
Hmm. Interacting with upstream Electron has not been fun for me in the past. I have a PR up for a requested feature, but no review. Maybe if I find some time I will look into it. Thanks for the info.

**Comment by klinker24** [comment]
I am going to close this one. I do a pretty good job of watching updates on Electron builder. If it becomes available, I will be sure to enable flatpak.
