### ISSUE TITLE
Messages won't send (on proxy)

### ISSUE THREAD

**Issue by csm10495** [klinker-apps/pulse-sms-issues#948]
## Confirm this Issue

- [ x ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [ x ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [ x ] I have verified that this is something that is reproducible.
- [ x ] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Device/Platform Information

**Device with issue:** Windows 10 Desktop
**Primary device:** Windows 10 Desktop
**App version:** v4.1.0

## Describe the Bug

New messages can come in, but I can't seem to send any from the Windows App.

### Steps to Reproduce

1. Be on a system that requires a proxy to send messages
2. Try to send a message
3. Hit refresh (the message will disappear)

### Expected Behavior

The message should send. Or some error should be given if something is wrong.

### Screenshots

![fail_to_send](https://user-images.githubusercontent.com/5749838/71855651-7a1a6800-3096-11ea-863e-01f98fa955a0.gif)
After hitting send, waited a moment then hit refresh.

### Additional Information

NA

**Comment by klinker24** [comment]
Pulse uses Google Play Services to deliver messages from the web to the device to be sent. If they are not sending, you can refresh your account to reset the connection. If that does not solve it, then you will need to get in touch with whomever runs your proxy. 

https://messenger.klinkerapps.com/help

They will not display an error, because they are still in the queue to be sent.

**Comment by csm10495** [comment]
@klinker24 , i believe you have closed this a bit prematurely. If I send messages from the website instead, it works (on the same computer). When sent via the app, they never get to the phone to send.

The proxy works fine with numerous other applications and used to work here too. Really seems like a possible regression. Why would messages only come in one direction (getting them but can't send them)?

**Comment by klinker24** [comment]
I mean, you were the one that originally set up the proxy support for the app: https://github.com/klinker-apps/pulse-sms-desktop/pull/4

I really know nothing about it and have had no reports of issues from others.

**Comment by csm10495** [comment]
Fair enough. I had run into issues trying to build the app recently when
trying to debug this. (Something about electron... different problem). Kind
of unfortunate that there are so few app logs... makes it harder to debug
without digging deeper.

... I'll try to debug a bit more if i can get the app building again.

- Charlie Scott Machalow
