### ISSUE TITLE
'cp' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by csm10495** [klinker-apps/pulse-sms-issues#949]
When running yarn start on Windows, we get the following error:

```
PS C:\pulse-sms-desktop> yarn start
yarn run v1.21.1
$ yarn run build && electron .
$ tsc && cp -r src/assets built/assets
'cp' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
On windows the command to copy should be ```copy``` though on Unix-like it is ```cp```

**Comment by klinker24** [comment]
If you wanted, you could make a `start-windows` command and add it to the `package.json`. I don't think I will change the `yarn start` command though. 

You could also just use a bash terminal and it would work perfectly fine. [Git bash](https://gitforwindows.org/) for example.
