### ISSUE TITLE
Hide private conversations content from recent apps screen

### ISSUE THREAD

**Issue by ArTruong** [klinker-apps/pulse-sms-issues#950]
Hi Dev,

I know PulseSMS already support PIN/FingerPrint to view private conversation
I add this feature request because I think there are some services like Bank still support 2FA via SMS so if PulseSMS should support security when open app and hide content when user using "Recent App" to improve security more.

Thanks,
Aries Truong

**Comment by klinker24** [comment]
In the future, please follow the issue templates that I have set up. 

I do not plan on adding authentication to the app itself, sorry. Private conversations are the only place that I want to authenticate you (with fingerprint or PIN). I can look into hiding the content on the of the private conversations page, on the "recent apps" screen.
