### ISSUE TITLE
Allow Android App To Work On Degoogled Devices

### ISSUE THREAD

**Issue by trymeouteh** [klinker-apps/pulse-sms-issues#951]
PulseSMS is now open source which is great news and hopefully soon someone will get the app onto F-Droid. The problem now is that the app requires Googles proprietary code which means it will not work on Android devices that are Degoogled.

The functions that I know do not work is sending/receiving messages on paired devices which is a major issue since that is what PulseSMS is known for. Please allow PulseSMS to work on privacy friendly Android devices.

PulseSMS itself respects users privacy by encrypting the text message when its being transferred between devices and as it is stored on the cloud, and for PulseSMS to be open source. Please find alternative ways to use open source libraries to make it work on all Android devices Googled or Degoogled.

**Comment by klinker24** [comment]
Sorry, Pulse is just not going to work without Google play services. It was totally architected around FCM, this is not something that I plan to change or re-architect. That is just not at all a priority for me. While I understand some people don't want the app to touch Google, that isn't something I have an issue with at all.

Without Google services, the app will work totally fine on your phone. The backend for Pulse is not open source, nor is it something that I plan to open source. As such, someone would have to recreate the API without that reliance and fork the Android, web, and other platforms to make them work on a different backend. While it is possible, that is not something that I personally have plans for, nor is it something I would ever officially support.
