### ISSUE TITLE
Updating Android Notifications to Show Only Most Recent Message

### ISSUE THREAD

**Issue by sstream17** [klinker-apps/pulse-sms-issues#956]
## Confirm this Issue

- [x] This is something that I am looking to code myself and create a PR for, not a feature request for @klinker24 to code.
- [x] This is a change that I am considering, which I would like feedback on, to discuss implementation details, or to confirm whether or not this is something that would be merged into the app.

### Describe Your Request

When the user has the history_in_notifications preference disabled, instead of being notified only of the most recent message, notifications append the most recent message onto the end of the notification. This makes it difficult to see the most recent message without expanding the notification.

<table>
<th colspan="2">Before</th>
<tr>
    <th>Notification Arrived</th>
    <th>Notifications Expanded</th>
</tr>
<tr>
    <td>
        <img src="https://user-images.githubusercontent.com/38381547/72570544-dcd3e680-3882-11ea-9941-0bdb3adbd27b.png" alt="Old Notification Arrived" width="300">
    </td>
    <td>
        <img src="https://user-images.githubusercontent.com/38381547/72570564-e52c2180-3882-11ea-8875-58591174f9db.png" alt="Old Notifications Expanded" width="300">
    </td>
</tr>
</table>

I think it would be better to show only the most recent message when the notification arrives, but still keep the history of unread messages when the notification is expanded. This behavior is similar to how the notifications currently behave, but it makes it easy to see the most recent message when it first comes in.

<table>
<th colspan="2">After</th>
<tr>
    <th>Notification Arrived</th>
    <th>Notifications Expanded</th>
</tr>
<tr>
    <td>
        <img src="https://user-images.githubusercontent.com/38381547/72570582-eeb58980-3882-11ea-9aa9-560ad94df1ab.png" alt="New Notification Arrived" width="300">
    </td>
    <td>
        <img src="https://user-images.githubusercontent.com/38381547/72570598-f5440100-3882-11ea-8957-2085993dd967.png" alt="New Notifications Expanded" width="300">
    </td>
</tr>
</table>

I am achieving this by updating the `NotificationConversationProvider.buildMessagingStyle()` method. [When adding the message](https://github.com/klinker-apps/pulse-sms-android/blob/55670e649564b160c6fba98a79d88c1318b75e99/shared/src/main/java/xyz/klinker/messenger/shared/service/notification/conversation/NotificationConversationProvider.kt#L254) to the `messagingStyle`, it checks if the user has enabled the history_in_notifications preference or if the message has not been read. This allows the prior, unread messages to still appear when the notification is expanded and the history preference is turned off.

Do you think this is the best solution to the problem? I notice there is also a `seen` variable, but I think checking if `read` makes the most sense here. I was also thinking about checking if the message was from someone other than the user, but we may not want to include this because I hypothesize it would affect inline replies. Currently, inline replies work and the reply adds itself to the conversation in the notification.

Let me know what you think of this feature. It is ready for a PR if you want this change.

**Comment by klinker24** [comment]
This is actually working the way that I designed it and want it to work..  the `seen` property gets set to `true` whenever the notification is dismissed, indicating that the message has been read. When building the notification, the content text on the notification will only display messages that are not `seen`. So if you don't dismiss the notification, then the content text on the notification would show the previous messages, as you demonstrate in your screenshot. If you dismiss the notification or open the conversation though, the next notification to come in would only display the most recent message.

This is definitely working the way I would expect and have it designed. Are you referring to something different? I do not want to remove the previous messages from the notification if they are not marked as `seen`

**Comment by sstream17** [comment]
The problem is the most recent message is not shown if the first message is too long.
For example, here is the notification that is shown after a second message is sent in succession.

<img src="https://user-images.githubusercontent.com/38381547/72574157-b23b5b00-388d-11ea-85c6-dff687397437.png" alt="Second Text Arrived" width="300">

It does not show the new message at all, only the first message. If you expand the notification, you can now see the second message which was sent.

<img src="https://user-images.githubusercontent.com/38381547/72574223-ea429e00-388d-11ea-9db4-acc760074ea5.png" alt="Notifications Expanded" width="300">

The user then is not notified of the correct message which has most recently arrived. My change allows only the most recent notification to appear in the heads-up notification. In this case, the notification would read "Okay here is the second message." instead of just the start of the first one. Both messages are still able to be viewed in the expanded notification until they are marked as read. I think this change provides a more accurate experience to the user and prevents "duplicate" notifications even though a new message has arrived.

Please let me know if you have any questions.

**Comment by klinker24** [comment]
Right, but if the first message in the chain is not marked as seen, then the app should show the first message, rather than the new one. The app is going to show the message first unseen message, so that the user can read it first. This is definitely working the way that I have designed it to work and think that it should work

**Comment by klinker24** [comment]
Pulse doesn't and can't know if the user has pulled down the notification and examined the first message. So it has to assume that the user has not.

**Comment by sstream17** [comment]
I just want to make sure we are on the same page.

This is the current behavior of notifications with 'Show Conversation History' off:

1. Contact 1 sends first new SMS:
"This is the start of the first message. This is the middle of the first message. This is the end of the first message."
2. Notification pops up with text:
"This is the start of the first message. This is the mi..."
3. Contact 1 sends second new SMS:
"Here is the second message."
4. Notification pops up with text:
"This is the start of the first message. This is the mi..."

As a user, I want to see the text of the SMS triggering the notification so that I do not miss any new information.

The behavior I would expect from this situation is:
1. Contact 1 sends first new SMS:
"This is the start of the first message. This is the middle of the first message. This is the end of the first message."
2. Notification pops up with text:
"This is the start of the first message. This is the mi..."
3. Contact 1 sends second new SMS:
"Here is the second message."
4. Notification pops up with text:
"Here is the second message."

This behavior is consistent with other notifications and is actually what happens when the user has 'Show Conversation History' on. Displaying the first message again upon arrival of new SMS goes against platform conventions. Users expect the most recent SMS, the one which triggers the notification, to appear in the notification's text. When that doesn't happen, they may think something is misbehaving.

**Comment by klinker24** [comment]
I just do not agree, sorry. The behavior is different between the two styles because the styles themselves are just different. 

When that option is turned off, the user is expecting to see the content of the messages that they have not seen before. I show the content of the first message as well, since it has not been seen. The user cares about the content that they have missed, they don't know or care which message generated the notification. Since the first message is not marked as `seen`, then they are saying that they want to see that. I do not agree that this goes against any platform conventions. Both messages are part of the content that the user has missed and should be combined so that the user can see what they missed. Whether or not the first message is "too long" just doesn't matter. The content of that message has not been seen, so the contents of that message should be shown.

When the "show conversation history" option is turned on, the style itself only ever displays single messages. It does not ever combine multiple messages, so single messages are also displayed as the content text of the notification. The styles are just different

Sorry, this is just not something that I am looking to change. In my opinion, as a user and a developer, this is working as expected. This case is the entire point of the `seen` flag on messages.
