### ISSUE TITLE
Web Contact Thumbnail Pictures - What is the estimated timeframe?

### ISSUE THREAD

**Issue by quicksite** [klinker-apps/pulse-sms-issues#957]
*Please read my notes, then replace my notes to fill in this template with your own information and check the boxes to confirm you understand the request.*

## Confirm this Issue

- [x ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.
- [x ] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Describe Your Request

I could not find this item here on github. I did read your help pages where you say:

> Right now, contact pictures only live locally, on the phone. In the future, they will expand to the web as well.

**Contact Image problems with Google Messages, specifically for Shortcode Provider Messages, was the primary reason I switched to Pulse.** I was very happy with Google Messages until approx October/Nov 2019 when Google began some kind of Business Verification process along with architectural changes to use RCS— which suddenly eliminated Contact images for business shortcodes, from banking & security verifications to Amazon delivery status updates. Tons of threads on their product forums re Shortcode Images stripped both on their Android and Web apps, and Google as usual silent & non-acknowledging.  Many people bailing based on no indication whatsoever when the issue will get corrected.

This might seem picky but for SMS messaging, **I rely more than 50% of the time on sending & receiving on my computer** as opposed to my phone. So that's a pretty significant feature for me, and I know for many others as well.  In addition, tons of people rely upon visual scanning of SMS conversation icons, vs having to click to see who is sending what.  Examples abound, such as when you get heads-up notifications that pop up for just a second or two: It is far easier to be able to identify if it is something urgent or something you can ignore for now when the icon is the logo of the particular business, etc.

Additionally I have ADHD, and for me, **pictorial visual cues — icons, thumbnail photos, color-coding — all provide the highest productivity gains and dramatically reduce cognitive load** from having to engage and scan down text blocks to prioritize tasks and actions.  While I understand that presently you offer the ability to choose different colors to represent different Contacts, this has not been successful for me at all. 9 times out of 10 the randomly assigned colors are far too light, making readability very poor with white type on lighter colors.  

I would like to see from user responses, if any, how important this feature is for other people.

### Describe alternatives you've considered

I have tried the differentiated Contact Colors, but as stated above, they are almost all way too light in value, and readability is quite terrible with white type over lighter colors.

### Additional information

![luke pulse sms copy](https://user-images.githubusercontent.com/128756/73244434-c836fe80-415e-11ea-8ca5-612cbe3fe06c.png)

**Comment by klinker24** [comment]
When #133 is done, this will be included. Sorry, I cannot and will no be able to provide estimates or ETAs. I include features as quickly as I am able and prioritize them by how large of an impact I feel they will have. Thanks for letting me know that this is something that you are interested in having.
