### ISSUE TITLE
Manual MMS Download

### ISSUE THREAD

**Issue by Klexur** [klinker-apps/pulse-sms-issues#960]
## Confirm this Issue

- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.
- [x] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Describe Your Request

Option to manually download MMS (be it a picture or group message). I prefer not to leave my data on all the time.

### Describe alternatives you've considered

I've found no solution within Pulse. Alternative texting apps (like chompSMS, Textra, and YAATA) support this option already when data is turned off by providing a notification with a download button.

**Comment by klinker24** [comment]
We track all MMS requests and issues on #101, this is now linked there. This is something I would like to add in the future.
