### ISSUE TITLE
Different color for each sim card

### ISSUE THREAD

**Issue by super-kalou** [klinker-apps/pulse-sms-issues#961]
Hi!

you can plan in a next update to be able to choose a different color for each Sim card to avoid making mistakes when sending SMS and have a little icon in the corner of each conversation with the color of the sim

Thanks 👍

**Comment by klinker24** [comment]
Pulse uses colors on a per-conversation basis, not per SIM, so that isn't something that is planned, sorry.  

Within any conversation, there is already a little SIM icon that indicates which SIM you are sending from. It is right next to the attachment button.
