### ISSUE TITLE
i18n error on lock_screen's notification when more 1 unread senders

### ISSUE THREAD

**Issue by karakum** [klinker-apps/pulse-sms-issues#962]
## Confirm this Issue

- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [ ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [X] I have verified that this is something that is reproducible.
- [ ] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Device/Platform Information

**Device with issue:** Samsung SM-A520F
**Primary device:** Samsung SM-A520F
**App version:** 5.1.0.2697

## Describe the Bug

When there are more than one unread SMS from different senders, notification on LockScreen contain something like i18n-error : 
"Исходный язык не содержит эту множественну.."
![изображение](https://user-images.githubusercontent.com/12033941/73912261-a409b900-48e6-11ea-9e7d-3da529b53c32.png)

Also my security options disallow showing notification content on LockScreen.

### Steps to Reproduce

1. Got 2 SMS from different senders. Do not read it.
2. Lock screen
3. See error

### Expected Behavior

I think there must be somthing like "You have X unread messages from Y senders"

**Comment by karakum** [comment]
@klinker24 I just fix your lines for correct RU plural forms there https://github.com/klinker-apps/pulse-sms-android/pull/52
Thanks

**Comment by karakum** [comment]
@klinker24 I confirm that in 5.1.1.2706 version issue still present

**Comment by karakum** [comment]
I've try to check translations in OneSky... and I'm little confused...
![изображение](https://user-images.githubusercontent.com/12033941/74024840-37b9b300-49d5-11ea-88ba-360dcc80765f.png)

It seems, that it is translate engine's issue. 
"Source language does not contain this plural form" - but it does't has to contain. All languages are different. In EN there are 2 forms, in RU - 4 forms.

**Comment by karakum** [comment]
msg "#27262444" was missed. I fix it on OneSky

**Comment by klinker24** [comment]
I haven't updated the app with the changes. `v5.1.1` has been available for a few days.
