### ISSUE TITLE
New Contacts Don't Appear in App Search Context

### ISSUE THREAD

**Issue by Serubin** [klinker-apps/pulse-sms-issues#965]
## Confirm this Issue

- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.
- [x] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Device/Platform Information

**Device with issue:** Pixel 3 Android 10 & All Platforms
**Primary device:** Pixel 3 Android 10
**App version:** Ex: v5.1.1.2706

## Describe the Bug

New contacts do not show up in search contexts on the app or on other platforms. It seems as though the app is not resyncing with the contacts database on the phone and thus no platform can see the new contacts. 

The correct names do come up if a) they text me or b) I manually enter their number. _it is limited to the search/compose context_

### Steps to Reproduce

1. Add a contact, ensuring a mobile number exists
2. Re-launch pulsesms
3. Compose a new message, start to type their name
4. Their name will not show up

### Expected Behavior

The expectation is that any contact should show up when searching for them.

### Additional Information

This has been an issue for a few months - potentially 4-6 months.

**Comment by klinker24** [comment]
It has always been an issue. Pulse doesn't upload new contacts to the web unless you go through the "resync contacts" process

#740

**Comment by Serubin** [comment]
@klinker24 I'm not referring to the web - I'm referring the android app itself. Since the app doesn't see the contact, the web can't either.

**Comment by klinker24** [comment]
Hmm, Pulse cannot control what shoes up in the android app. All it can do is ask the contact provider what contacts match "<this search query>".

**Comment by Serubin** [comment]
Update - it seems search doesn't really work at all right now. 

I'll try wiping app data and see if that helps.

**Comment by klinker24** [comment]
Is this still an issue?

**Comment by Serubin** [comment]
Wiping the app seems to have fixed the issue.

**Comment by klinker24** [comment]
Ok, closing then. Feel free to re-open if something else comes up or there are more details

**Comment by ted1735** [comment]
What does new constitute? I have contacts added on Feb 4th that still show up as phone numbers. So we need to clear app data anytime this happens? Yet when I click on the details it shows the contract info and picture.
![20200303_214230](https://user-images.githubusercontent.com/515277/75840159-9d148000-5d98-11ea-8a3e-1821d24692cd.jpg)
![20200303_214027](https://user-images.githubusercontent.com/515277/75840161-9d148000-5d98-11ea-94e8-57cb613c0c3a.jpg)
![20200303_214108](https://user-images.githubusercontent.com/515277/75840162-9dad1680-5d98-11ea-8cfa-2d1e25e66219.jpg)
