### ISSUE TITLE
sending messages fails in pulse android app 

### ISSUE THREAD

**Issue by paymanz** [klinker-apps/pulse-sms-issues#966]
sending messages fails in pulse android app . it immediately fails! how can i solve it?
![463503314_483170](https://user-images.githubusercontent.com/10323812/74233632-4e674f00-4ce0-11ea-98f9-360e5d9e4687.jpg)

**Comment by klinker24** [comment]
Failures come directly from your carrier and are not generated by Pulse. I cannot control it if the status of your messages are "failed".

You can try restarting the phone to reset any carrier connections. You could also reinstall the app to reboot the connections. 

All that Pulse can do is hand off messages to Android to be sent. The sending process is out of my control.

**Comment by paymanz** [comment]
> 
> 
> Failures come directly from your carrier and are not generated by Pulse. I cannot control it if the status of your messages are "failed".
> 
> You can try restarting the phone to reset any carrier connections. You could also reinstall the app to reboot the connections.
> 
> All that Pulse can do is hand off messages to Android to be sent. The sending process is out of my control.

i re installed app , also i have no problem with other unofficial messaging apps. thanks for replay
