### ISSUE TITLE
Stuck in Fullscreen

### ISSUE THREAD

**Issue by scottidler** [klinker-apps/pulse-sms-issues#967]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.

## Device/Platform Information

**Device with issue:** System 76 on Ubuntu-19.10_x64(eoan), running Firefox 73.0 (latest)
**Primary device:** Pixel 4 XL on Android 10, feb 10 2020 (latest)
**App version:** pulse-sms-4.1.0-amd64.deb

## Describe the Bug

Can't get out of fullscreen mode for pulse-sms desktop application.

### Steps to Reproduce

1. Installed app
2. clicked fullscreen
3. stuck

Reinstalled the app, and the same thing.

### Expected Behavior

There should be some way to get out of fullscreen.

### Additional Information
I checked the issues, I looked for a preference or config file on my system.  I read docs on fullscreen mode in Electron Apps.  I searched for keyword fullscreen in the repository.

**Comment by klinker24** [comment]
I am not really sure what you mean or what I am supposed to be able to do about this, sorry. Your system manages the "full-screen" status, Pulse has nothing to do with that. 

Pulse doesn't know when you are full screen and it really doesn't care. It's UI is simply adaptive to adjust to any screen size. 

This is ubuntu's documentation on maximizing windows: https://help.ubuntu.com/stable/ubuntu-help/shell-windows-maximize.html.en
