### ISSUE TITLE
Xiaomi mi9t Android 10

### ISSUE THREAD

**Issue by danimusicos** [klinker-apps/pulse-sms-issues#968]
*plus de notifications sonores alors que l'application xiaomi est ok

## Confirm this Issue

- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.
- [x] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## xiaomi mi9t
Android 10

**Device with issue:** Ex: MacBook Pro on MacOS 10.12, running Chrome v54
**Primary device:** Ex: Pixel XL on Android 9
**App version:** Ex: v4.1.5

### Steps to Reproduce

`... more steps`

### Additional Information

Add any other context about the problem here. Device configuration, unique cases, anything that you think may be relevant.

**Comment by klinker24** [comment]
Pulse has absolutely no control over your notifications in Android 8.0+. All of this is managed through the system level notification channels. You can long click any notification to access the settings for that channel. My app has no control at all over how notifications alert you.

**Comment by danimusicos** [comment]
OK. Donc bug sur miui 11 et où Android 10 car j'ai tout essayé. Bye

⁣Télécharger BlueMail pour Android ​

Le 22 févr. 2020 à 14:51, à 14:51, Luke Klinker <notifications@github.com> a écrit:

**Comment by danimusicos** [comment]
L'apk de message xiaomi fonctionne parfaitement. J'ai essayé plusieurs fois de voir chacune des fonctions. J'ai installé textra, chomps, mood, les notifications sonores fonctionnent ! À voir car pour le coup si les autres fonctionnent pourquoi pas pulse ?
