### ISSUE TITLE
(feature request) Set automatic prefix to programmed message

### ISSUE THREAD

**Issue by Ilithy** [klinker-apps/pulse-sms-issues#971]
Good morning, sir,
I regularly send scheduled messages (thanks for this very handy feature), but often at hours when I'm asleep (it's professional), to avoid that the person does not answer me immediately after receiving my message, I systematically add at the beginning of the message this:
[Scheduled message] ...

Would it be possible to add an option to include, in the same way as the signature (at the end of the message), the possibility to automatically place a user-defined text at the beginning of all programmed messages?

This would be extremely useful,
thank you very much.

**Comment by klinker24** [comment]
Sorry, I really don't think that this is something that I will add to the app. Feel free to implement it yourself if you are interested

https://github.com/klinker-apps/pulse-sms-android

I just don't see enough use case out of this. The point of scheduling messages isn't to notify the user that they are scheduled, it is just to push off that message until later. I guess I just don't really see a reason to notify the other person that they are scheduled. In a professional setting, I do not think that notifying them that you pushed off that message to later is appropriate.
