### ISSUE TITLE
Screen overscan

### ISSUE THREAD

**Issue by dtr145r** [klinker-apps/pulse-sms-issues#972]
*Please read my notes, then replace my notes to fill in this template with your own information and check the boxes to confirm you understand the report that you are filing.*

## Confirm this Issue

- [ *] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [ *] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [ *] I have verified that this is something that is reproducible.
- [* ] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Device/Platform Information

**Device with issue:** pixel 4 xl
**Primary device:** Ex: Pixel XL on Android 9
**App version:** Ex: v4.1.5

## Describe the Bug

When selecting to type text the keyboard will pull up but the space where you type doesn't. I can still type and it registers however I can't see it. I have to back out of the conversation thread and go back in to see it.
### Steps to Reproduce
Open app.
Select text thread 
Try to type.
This app doesn't play nice with https://play.google.com/store/apps/details?id=com.fb.fluid
Pulse is the only app that doesn't work with it..

### Expected Behavior
Expected to see what I'm typing.

### Additional Information

Add any other context about the problem here. Device configuration, unique cases, anything that you think may be relevant.

**Comment by dtr145r** [comment]
![Screenshot_20200306-192426](https://user-images.githubusercontent.com/61892740/76132445-16061880-5fe1-11ea-8b4f-d6cd7051faff.png)

**Comment by dtr145r** [comment]
![Screenshot_20200306-192437](https://user-images.githubusercontent.com/61892740/76132461-2ddd9c80-5fe1-11ea-924c-4c58a931f925.png)

**Comment by klinker24** [comment]
If you wanted to fix this, you could build a custom version of Pulse and return `false` from this method

https://github.com/klinker-apps/pulse-sms-android/blob/90d9a24f99615cfff89a63cc2b38c595cc282807/shared/src/main/java/xyz/klinker/messenger/shared/util/ActivityUtils.kt#L170

Personally, I am not going to make changes to support a root-only app like that. If having a self-built version of the app isn't enough and you want it in a production build of the app, then you should submit a PR to add a preference into the open source experiments menu, then maintain this preference

https://github.com/klinker-apps/pulse-sms-android/blob/90d9a24f99615cfff89a63cc2b38c595cc282807/shared/src/main/java/xyz/klinker/messenger/shared/util/ActivityUtils.kt#L170
