### ISSUE TITLE
Messages duplicating and incorrect ordering

### ISSUE THREAD

**Issue by kirindad** [klinker-apps/pulse-sms-issues#973]
I have noticed that when I am actively messaging (Android 10 phone, Android 8 Tablet, Web) often responses I get appear higher up in the message list than the message that I sent that was replied to .  Also I occasionally see duplicate responses. There must me something wrong with the time stamping or how stamps are being read by the clients.  It is not limited to a particular device or user. I am in the latest version, and see this issue across all devices, which makes me think it is a server side or DB issue.

**Comment by klinker24** [comment]
One of your devices doesn't have the same timestamp as your other devices. Timestamps aren't written on the server side, they are written on your device side. 

* When you send a message, it will use the timestamp from the device you sent the message from
* When you receive a message, it will use the phone's timestamp

This structure is not something that is planned to change on my end.
