### ISSUE TITLE
Sync Contact Photos

### ISSUE THREAD

**Issue by piticent123** [klinker-apps/pulse-sms-issues#976]
## Confirm this Issue

- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.
- [x] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Describe Your Request

Currently, contact photos from my phone don't sync to the desktop app. I'm aware (according to the FAQ) this is intended behavior.

### Describe alternatives you've considered

I used Android Messages (or whatever it's called now) for a while, but truth be told, their solution is only half baked - the pictures show up in the website, but not in notifications. I'm not sure if this is a limitation of web notifications. I haven't looked into the APIs

### Additional information

I wasn't sure if this was something you were willing to at some point do. It seemed based on the FAQ the answer is no, but I do see a mention in #133 that you would be interested in putting it on the road map, so I figured I'd make an official feature request to see what your thoughts are. It would probably pair well with #133 if I had to guess.

**Comment by klinker24** [comment]
This will come when #133 is done.
