### ISSUE TITLE
Phone call from computer

### ISSUE THREAD

**Issue by Thelm76** [klinker-apps/pulse-sms-issues#980]
## Confirm this Issue

- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.

> maybe https://github.com/klinker-apps/pulse-sms-issues/issues/704 but not sure

- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.

> I looked, but there are so many topics that I maybe missed it

- [X] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Describe Your Request

I'd like to see a feature that permits to call someone from a computer (or another connected device) instead of the phone itself.

### Describe alternatives you've considered

(Software)
Alternatives would probably be to get another app from the store, but it would also replace the sms part, and this is not the goal.

(Hardware)
Another alternative would be to connect the phone to the computer by using a specific cable or bluetooth, but this looks overly complicated.

### Additional information

I know this could be considered as a dumb request as this is a messaging app, not a "call from computer" app.
I also know that this could be a lot of work for programming and updating such a feature;
But I think it would be a "nice to have" as the app would be more versatile.

**Comment by klinker24** [comment]
Sorry, this isn't something that I currently plan to do. 

Pulse is meant to be a messaging app, its architecture is designed around messaging, not phone calls. It is not set up at all to support something like this.  Phone calls would be a completely different implementation and it just isn't something that I am really interested in bringing into Pulse. That just isn't the goal of the app or its architecture.

**Comment by Thelm76** [comment]
Thank you for the quick reply, that's what I was thinking but I had to ask to be sure.
By the way your app is awsome, really like it.
