### ISSUE TITLE
Contact names & pictures not updating in Pulse

### ISSUE THREAD

**Issue by bry-huang** [klinker-apps/pulse-sms-issues#982]
Device: This is happening on both my phone (Pixel 2 XL on Android 10, Pulse app version 5.2.3.2731) and my Macbook Pro running Catalina (10.15.4) running Pulse via Franz.

Edits to contact names & picture do not update in the Pulse app.  When I go into a contact on my phone and add a picture or edit their name (like adding a last name at a later date), the name & picture in the Pulse app doesn't update.  I've tried restarting my phone and computer and closing & reopening the app, but I can't get these names to refresh.

Steps:
1. Enter a new contact in the phone's Contacts app w/ phone number
2. Start a text conversation with that person in Pulse
3. Go back to Contacts and update the name
4. Reload Pulse and notice the name doesn't refresh

**Comment by klinker24** [comment]
You can update the title of a conversation by opening that conversations settings menu.

To update the contact image, you will need to clear the app's cache, through your system settings.

https://messenger.klinkerapps.com/help

**Comment by bry-huang** [comment]
Thank you!  I didn't know the conversation title was a one-time import of the contact's name.  I'll update my conversation titles moving forward.

I tried clearing the app's cache through my system settings but pictures still aren't updating in Pulse.  Any other things I can try?
