### ISSUE TITLE
Calendar option to view messages/media by date

### ISSUE THREAD

**Issue by joyceling** [klinker-apps/pulse-sms-issues#983]
*Please read my notes, then replace my notes to fill in this template with your own information and check the boxes to confirm you understand the request.*

## Confirm this Issue

- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.
- [X] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Describe Your Request

I find that I use my messaging as a source of history, to help me remember what happened during certain times. However, it's difficult to go back to a specific point in time without scrolling through each message individually. The feature I have in mind isn't just scrolling back to the date for an individual message - it would be a layout of ALL messages/media exchanged on the platform on that date. 

### Describe alternatives you've considered
A calendar view. You could open the calendar and select a day, which would open up a view of ALL messages and media that you received around that time. Perhaps messages/media are in the same grouping, but it might be helpful to keep them separate as well. 

A good example of this is in the messaging platform for couples, Between. I've attached a screenshot of how their calendar looks. There's a dropdown menu on the actual chat itself, and on the menu is a calendar icon which opens the calendar view. There's a highlighted number of how many messages/media were exchanged on that day, if there was anything exchanged on that day. When you tap on the date, it scrolls to the point in time in that conversation. In Pulse, it would be like... searching the date and pulling up all the chats that came up around that time, but with a cleaner calendar UI. 

![Screenshot_20200407-084813_Between](https://user-images.githubusercontent.com/30604472/78678404-850bb100-78ae-11ea-9192-c20400ef4204.jpg)

**Comment by klinker24** [comment]
If you drag the scrollbar on the side of any conversation, it allows you to quick scroll to any date. I do not see any advantages of a calendar over this sort of quick scroll. Both will quickly allow you to find the date you are looking for.

I don't really understand the other half of your request. You want to combine the messages from all of the conversations, on that given date? I do not think that this would be useful. You would lose the context of those messages and conversations. Random messages on their own do not really provide the big picture of what is going on at a time: conversations do. Please clarify, but if that is what you are looking for, I do not think that that is something that I will be adding into the app, sorry.

**Comment by klinker24** [comment]
I am going to close this for a lack of response/clarification. Feel free to come back and comment if you wish to clarify what you are looking for.
