### ISSUE TITLE
Cannot send multimedia messages

### ISSUE THREAD

**Issue by Groundcontrol38** [klinker-apps/pulse-sms-issues#984]
I can't send multimedia messages using the pulse app.  Sending multimedia messages using the built in Samsung messages app works like it is supposed to.   I have had this issue for a couple if months and thought that i solved it when i turned my mobile data back on and some messages went through.   Now,  they will not go through even when my mobile data is on.   I tested sending to other android phones and iPhones.  I cleared the apps cache and the data but that did nothing.   I reset all of my app permissions and that did nothing.   I found out that the pulse app was the problem because i switched the default app back to messages and was able to send multimedia messages.  When i did that,  a weird thing happened,  the messages app started sending old multimedia messages that i had tried to send over the last couple months with pulse like they were stuck.  I have a Samsung galaxy S9+ on Xfinity mobile.

**Comment by klinker24** [comment]
I will not be able to control what your stock app does when it is set as the default. 

On my help page, the first topic in the MMS section has a list of troubleshooting tips for issues around MMS

https://messenger.klinkerapps.com/help

At this time, those are the only tips I have and will work for the vast majority of cases. We track all MMS issues on #101 though. This report has now been linked there.
