### ISSUE TITLE
Widget not working

### ISSUE THREAD

**Issue by felipeoliveiranet** [klinker-apps/pulse-sms-issues#986]
Hi,

Thanks for this awsome app \O/

I added Pulse SMS Widget in my home screen, at first it works show messages list, but if I click in any item, nothing happens and + (new message?) doesn't work as well.

I searched for any issue about this and I can't find anything related.

I tried on Xiaomi Mi 9 no root / no SO changes at all

Thanks ;)

**Comment by klinker24** [comment]
Have you tried it with a different launcher? I haven't heard of any issues around the widget, but I will not pretend that I have tried it on every single device and launcher combination. Unfortunately I am not sure where to being looking for issues on this problem. Seems like the launcher isn't allowing the app to start its activities when things are clicked

**Comment by felipeoliveiranet** [comment]
Hey @klinker24 you are absolutely right.

I am using Nova Launcher, when I disabled and switch to MIUI default launcher, it work very well ;)

But I dont understand why this don't work with Nova, because I have others Widgets, like WhatsApp and Todoist and both works without any problem.

I tried to change permissions in Nova and Pulse wihtout success and have reinstalled Nova and Pulse, not change at all.

Do you have any hint of what could possibly be?

Thanks for the answer.

**Comment by klinker24** [comment]
Hmm, I have used the widget with nova in the past, and it worked fine then. I am not sure what would cause that, thanks for letting me know

**Comment by felipeoliveiranet** [comment]
Hi,

I tried right now with others launchers:

- Microsoft launcher, same problem
- POCO Phone, worked like default launcher, as both are from Xiaomi
- Smart Launcher 5, same problem

Do you recommend any other launcher to test?

Thanks

**Comment by felipeoliveiranet** [comment]
@klinker24 sorry to bother, but I found a fix for this problema in XDA forum.

I had to enbable "Display pop-up windows while running in the background" in App Settings for Pulse SMS, from -> https://forum.xda-developers.com/showpost.php?p=80913861&postcount=11

I don't know why this happens only for non-Xiaomi launchers, because other widgets work normally, but in that thread are others Apps Widgets having same problem, so the throuble is in Nova Launcher probably...

But thanks for answering \o/

**Comment by klinker24** [comment]
Hmm ok thanks for the follow up. I am going to close this then, and hopefully I can direct others here, in the future.
