### ISSUE TITLE
Voice to text on Samsung watch not working properly

### ISSUE THREAD

**Issue by bertg77** [klinker-apps/pulse-sms-issues#987]
I'm writing to find out if anyone has experienced difficulty with creating messages using speech to text on their Samsung watch like I have. Does anyone know if this can be fixed? There issue I have is that when writing or responding to a message, when I go to speech to text, the message only partially gets entered. This is very frustrating as I otherwise love pulse for my watch but prefer to speak into my watch to quickly write messages. Any insight into this matter would be greatly appreciated. Thanks

**Comment by klinker24** [comment]
Unfortunately Pulse has absolutely no control over text input. The keyboard and its functionality (including voice to text) is completely managed at the system level. You would have to bring this bug up with Samsung
