### ISSUE TITLE
Option to Auto-archive per-contact messages after # days

### ISSUE THREAD

**Issue by mentalfloss** [klinker-apps/pulse-sms-issues#988]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.
- [x] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Describe Your Request

Automatically Archive messages (and remove from conversation view) within a Contact's conversation that are older than a User-specified amount of days in Pulse's Settings.  This could be global for all contacts, and/or specific value the User can specify per-Contact.

### Describe alternatives you've considered

This is very similar to Clean Up Old Messages located in Settings->Advanced Settings, however the action would be Archive and not Delete as I want to keep the messages content to search for later.

### Additional information

My intent is to cut down on the amount of messages shown, but still retain them elsewhere so I can search through them in the future.  The amount of history shown when you go into a past message with a frequent contact (ie: wife/husband) gets quite long.

I know this may change the behaviour of Pulse as Archiving a conversation won't make them go away -- the next message that comes in will revive the entire history.  

I do want to keep the history to search in the future, however I don't want to see all 2000 messages in my default view when I add a new SMS to the conversation.

**Comment by klinker24** [comment]
Sorry, I do not want to change the way that the archive works. It is based on conversations, not individual messages.

If you swipe along the right side of the screen, it already has a quick scroll to whatever date you want. This is how the app will allow you to manage a large amount of messages, rather than archiving them.
