### ISSUE TITLE
Issue with device lacking play store

### ISSUE THREAD

**Issue by railed** [klinker-apps/pulse-sms-issues#989]
+ I have searched, by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
+ I have searched the help page to verify that it does not have any topics relevant to this issue.
- I have /somewhat/ verified that this is something that is reproducible, only trying 2 times with the same phones

Device with issue: Mi Mix 2S running lineageOS and microg
App version: Latest as of posting

Describe the bug:
From what I know, the developer isn't supporting degoogled phones. I get that but I'm not sure if microg counts as ungoogled, services requiring GCM or just play services work fine for me but not in-app purchases as those require the play store app, which is proprietary. Since Pulse has an account system I assumed that wouldn't be too much of an issue so I bought the lifetime service on a family members phone, made an account on that, but when I attempt to transfer over to my phone with no in-app purchase checks I get errors. Why is this if the account already is attached to a device that purchased the app?

Steps to reproduce:

1. Install Pulse SMS on a device with Google Play Services
2. Buy the lifetime subscription
3. Install Pulse SMS on a device with microg
4. Log into account on device with microg
5. Confirm you'd like to transfer the main device to the phone with microg
6. Error, account doesn't log in

Expected behavior:
Phone with microg would become main device and would be able to be accessed from other pulse clients.

Additional information:
I'm just not sure what I'm doing wrong :(

**Comment by klinker24** [comment]
Pulse relies heavily on Firebase Cloud Messaging to communicate messages between your devices. If you are seeing that error, FCM is not able to generate a token for the device and FCM will not work. 

Sorry, you are correct in assuming that I will not be supporting devices that do not have Google Play Services. The in-app purchases are not the only requirement for the Play Store and Google Play Services.
