### ISSUE TITLE
Chrome web app sent message does not appear on the top of the conversation list

### ISSUE THREAD

**Issue by DavidVlk** [klinker-apps/pulse-sms-issues#990]
*Please read my notes, then replace my notes to fill in this template with your own information and check the boxes to confirm you understand the report that you are filing.*

## Confirm this Issue

- [ x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [ x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [ x] I have verified that this is something that is reproducible.
- [ x] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Device/Platform Information

**Device with issue:** Windows 10 Chrome 81.0.4044.129
**Primary device:** Huawei P20 Pro Android 9
**App version:** Web app

### Steps to Reproduce

1. Go to pulsesms.app
2. Click on +, create new message, sent
3. The sent message does not appear on the top of the list
4. Pulse Chrome extension installed as well - when clicking on the Pulse extension the sent message is on the top of the conversation list in the extension and when going back to pulsesms.app it appears on the top of the conversation list too (but only after clicking on the extension)

### Expected Behavior

In the web app pulsesms.app the sent message should appear on the top of the conversation list.

### Additional Information
When sending another sms from the web app the sent sms does not appear at the top of the conversations again.

**Comment by klinker24** [comment]
I think that your expectation of how the app works is just a bit off and that that is causing your issue.

When sending through the "compose" screen on the web app, chrome app, desktop app, anything, it is not immediately sending the message or updating any of the conversation records. When you use the "compose" screen, it is forwarding whatever message you are sending to your phone to be sent. The phone app will then manage writing the message into the database, updating the conversations, and updating the conversation order. Nothing will change on the web side until the message is handled on your phone.

This is different than when you just open a conversation and send a message. When you do it that way, the web app will control writing the message to the database, updating the conversation, and updating the order. That is why you see this change reflected immediately.

The reason that this information is important is to highlight that when you send from the "compose" screen, nothing will be immediately changed. The conversation isn't going to immediately appear at the top of the list.  Your expectation is that it should immediately be reflected and that simply isn't the case. It will take a few seconds or more to appear in the list. It doesn't matter if you switch to the extension, go to a different screen, or anything like that. It just takes some time for it to be reflected in the UI. Going to the extension isn't speeding up the process. It is simply allowing more time for the message to be handled by your phone.

Is this the best way to do it? Of course not. But this is not something that is planned to change, at this time. 

It is just going to take some time for the message to be sent and the change to be reflected throughout your different app instances/platforms.

**Comment by DavidVlk** [comment]
Thanks for replying but what you are describing is now what I am seeing here and what I used to see before. What I am seeing is when using the Chrome extension the sent message appears on the top of the conversation list immediately. When using the web app the message does not appear at the top of the conversation list ever no matter how long I wait or what computer I try to use. To get the sent message to the top of the conversation list of the web app I either have to reload the page pulsesms.app or to click on the Chrome extension (opening the extension will move the sent message to the top of the conversation list of the web app as well). I am more than sure that previously till just a few days ago the sent message was appearing in the top of the conversation list of the web app immediately or in a moment. Thanks in advance for your further input on this matter.

**Comment by klinker24** [comment]
Hmm, the extension literally just show the web app's UI. The web app and the Chrome extension are exactly the same thing and would behave exactly the same way

https://github.com/klinker-apps/pulse-sms-web
https://github.com/klinker-apps/pulse-sms-chrome

I have just tested it and everything worked as expected on the web app, desktop app, Chrome app, and Chrome extension. Are you sure you don't have something set up within Chrome that would prevent the web app from setting up its websocket connection so that it could get immediate updates? There have not been any changes on my end around this.

**Comment by DavidVlk** [comment]
The same behavior appears on more machines. Let me know how to check that nothing prevents the web app form setting up its websocket connection. Just now I have noticed that: 1) when I click on the +sign and select a contact from contacts then the sent message does not appear on the top of the conversation list. 2) But when I select a conversation which is already on the conversation list, type the message and hit sent, then click on Conversation list, the send message appears on the top of the conversation list. 
If I follow the step 1 and click Conversations the message does not appear on the top of the conversation list.
The Chrome extension works the same way.
So I would say that what am I missing here is that the list of conversation should reload after sending an sms no matter if I am sending the message from a conversation which is on the list (this works ok) or sending a message from +sign and selecting a contact (this does not work / does not put the sent message to the top of the conversation list).
