### ISSUE TITLE
Draft messages appearing unexpectedly and not going away after deleting (likely draft syncing issue)

### ISSUE THREAD

**Issue by seesemichaelj** [klinker-apps/pulse-sms-issues#991]
## Confirm this Issue

- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [ ] I have verified that this is something that is reproducible. (I haven't figured out the exact steps to reproduce this)
- [x] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Device/Platform Information

**Device with issue:** Pixel 4 XL on Android 10
**Primary device:** Ex: Pixel XL on Android 9
**App version:** Ex: v5.3.0.2738

## Describe the Bug

As of last night, I will start writing texts in the Pulse app on my phone and proceed to send them. I will then lock my phone, and return sometime later only to find some substring of the message I already sent appearing as a draft (e.x "Hey! I have these free trials..." & more was sent, and only "Hey!" appears in the draft. It's not always limited to 1 word though, as another. Another instance was "Hey! Totally. Dinner is just arriving so you're both welcome to come over..." & more and only "Hey! Totally. Dinner is just arriving so you're both welcome to come" appeared in the ghost draft). I can clear the draft message, go Back to conversations, see that it is gone, wait some period of time, and the same substring draft reappears. I've tried force quitting the app as well as rebooting the phone.

My gut feeling is that Pulse's servers are storing draft messages to allow cross-device sync of draft messages. However, the sync mechanism to let the server know the draft is no longer a draft because it was sent or that the user has deleted the text. And then some period later, a resync happens on the client, pulling down the draft in the server despite it shouldn't exist anymore

This has happened with 2 separate conversations in the last 24 hours.

### Steps to Reproduce

I don't have specific steps to reproduce because this seems like sync logic, and I'm not sure how that sync logic happens, causing it to feel somewhat sporadic behavior as a user.

### Expected Behavior

**For a draft sync behavior across devices:**

- Whenever I send a message to a conversation, any and all drafts should be discarded on all devices for that conversation
- My current draft message should appear on all devices. As I modify the draft on one device, the 
- Deleting the text of a draft should delete the draft
- Rogue draft message should be able to be forcibly deleted from the server somewhere from the client. This is for the off chance the sync behavior doesn't work for whatever reason, or a hack until a better sync algo can be put in place. This could be a Draft Messages page which allows me to discard the draft which sends a query to the server telling it to definitely remove. This bullet isn't necessary though if the syncing algo works well

**Alternatively, for no draft sync behavior across devices (which is acceptable):**

- Whenever I send a message to a conversation, any and all drafts should be discarded on the device I'm currently sending on
- My current draft message should only appear on the current device and not other devices
- My device shouldn't think I have a `Draft: ...` message (when looking at the Conversations list) if the draft is an empty string

### Additional Information

I have a Lifetime Subscriber license, device ID 606409. I also keep a window open on my desktop with the pulsesms.app page open; perhaps there's an issue where my phone sends a draft to the server, the web app pulls the draft, phone finishes method, webapp sends draft to server, phone pulls draft? I could see there being concurrency issues here with multiple concurrent sessions

**Comment by klinker24** [comment]
I highly doubt that this issue has anything to do with syncing. I would guess that the problem is on the phone app.

If you can get steps to reproduce this, that would be helpful. I have not had any reports of draft issues, not have I seen issues with this myself.

**Comment by seesemichaelj** [comment]
I will try to engineer the reproduction steps.

**Comment by klinker24** [comment]
Reinstalling the app would probably be enough to fix it.

**Comment by seesemichaelj** [comment]
Reinstalling the app did not fix it. This ghost drafts appear in both the webapp and the android app.

I'm also now seeing "Draft: <ghost draft>" on the conversations page in both the Android app and the webapp, but when i click on the conversation (in both apps), there is no draft.

**Comment by klinker24** [comment]
Just create a new draft, then delete it, to clear out the old data from your account.

**Comment by seesemichaelj** [comment]
I've tried closing the webapp to prevent any sort of concurrency issues.

> Just create a new draft, then delete it, to clear out the old data from your account.

I just tried this with a different existing conversation:

1. start draft message
1. go to conversations list, verify the draft is there
1. click on conversation
1. delete text of draft
1. go to conversations list, verify the draft isn't there
1. wait some time
1. see draft reappear

Further, I'm now getting some pretty odd behavior:
- Conversations with these ghost drafts keep changing order on the conversation list (like multiple times a minute)
- With one of my conversations, I've tried deleting the draft and starting a new draft. Now that conversation changes which of those two ghost drafts to pick from

I'm not sure what you want to call this, but it sounds like there are clear syncing and/or caching issues from the Android app to the server. I'm going to try to now reproduce with the webapp without the Android app running

**Comment by klinker24** [comment]
If it is a sync issue, then refreshing your account would fix it. You can do this on the Android app.

Sorry, I do not have any other ideas or thoughts at this time.

**Comment by seesemichaelj** [comment]
>If it is a sync issue, then refreshing your account would fix it

This did seem to fix the issue, and my prior reproduction steps no longer reproduce.

However from one software engineer to another, this sounds like a hack until the sync state gets weird again. I have strong feelings you have concurrency issues with your sync logic, and you should highly consider edge cases before dismissing that your code "just works".

**Comment by seesemichaelj** [comment]
Closing for now; will reopen if this issue comes back

**Comment by klinker24** [comment]
Thanks for the tip. Not sure where I dismissed it, seeing as I have sat here with you troubleshooting, on a Sunday evening.

Have a nice night.
