### ISSUE TITLE
Dismiss notification should mark as read

### ISSUE THREAD

**Issue by IvoShoen** [klinker-apps/pulse-sms-issues#993]
*Please read my notes, then replace my notes to fill in this template with your own information and check the boxes to confirm you understand the request.*

## Confirm this Issue

- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.
- [ ] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Describe Your Request

A clear and concise description of what you would like to see, and why.

### Describe alternatives you've considered

A clear and concise description of any alternative solutions or features you've considered. There may already be something that is built into the app, or the platform, that is very similar.

**Comment by IvoShoen** [comment]
Dismiss notification should mark as read

**Comment by klinker24** [comment]
Sorry, this isn't planned. There is already a button to mark as read, on the notification.

**Comment by IvoShoen** [comment]
> Sorry, this isn't planned. There is already a button to mark as read, on the notification.

This in not helpful with dimmed screen notifications.
