### ISSUE TITLE
Rounded Message Bubble Style Very Square on Android

### ISSUE THREAD

**Issue by TChilderhose** [klinker-apps/pulse-sms-issues#994]
## Confirm this Issue

- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [X] I have verified that this is something that is reproducible.
- [X] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Device/Platform Information

**Device with issue:** OnePlus 7 Pro running Android 10
**Primary device:** OnePlus 7 Pro running Android 10
**App version:** `v5.3.0` and `v5.3.1`

## Describe the Bug

Since I received the `v5.3.0` update, my message bubbles have been very square even though I have `Rounded` set. If I go back to `v5.2.3` it seems to be fine. But as soon as I upgrade it goes square again. One thing I noticed is that if I tap a message bubble, it highlights as the proper shape. (See screenshots). But once it's selected it's highlighted as the more squared shape.

### Steps to Reproduce

1. Have `v5.2.3` installed
2. Have `Rounded` set as your `Message Bubble Style`
3. Observe that Messages look rounded like on other platforms
4. Upgrade to `v5.3.x`
5. Observe that Messages look more squared off

### Expected Behavior

Messages should look rounded like on other platforms

### Screenshots

![pulse1](https://user-images.githubusercontent.com/448815/82121814-df294d00-975d-11ea-9808-676b9339e7c3.jpg)

![pulse](https://user-images.githubusercontent.com/448815/82121817-e3556a80-975d-11ea-849b-440fea553984.jpg)

### Additional Information

I tried uninstalling and reinstalling and get the same thing. I've cleared caches and tried fooling around with different colors and different option combinations but they all result in the same thing. 

I unfortunately only have this one device so I can't try it on a different device. 

Let me know if there is something you'd like me to try or test.

**Comment by klinker24** [comment]
Hmm. This is the recent changes, I see nothing that would touch the message bubbles, not have I heard from others on this. Are there display density preferences on your device? I have absolutely no clue what would cause this or where to explore it, honestly.

https://github.com/klinker-apps/pulse-sms-android/commits/master

**Comment by TChilderhose** [comment]
Yeah, I went through the commits and didn't see anything that really stood out that would have touched that either. Originally I was thinking maybe there was a shared library that was updated but I'm now sort of wondering if the [update to Kotlin](https://github.com/klinker-apps/pulse-sms-android/commit/32eea59700dcc5cf79b386984bf79bcb264cb890) did something strange with layers/layouts on my version of Android? (I was an Android dev pre-Kotlin so not fully sure how the android-sdk and kotlin handle that stuff now). Cause that's the only thing I can see that maaaaybe could have done something but wasn't sure if there was some other shard repo stuff that you use in the build pipeline or not.

There are some different density preferences but I've always kept it the same. I did try different Density, font size, Display Scaling in the Android settings as well and they all reacted the same way.

**Comment by klinker24** [comment]
I can't see an update to kotlin causing density issues like that. It is extra weird that the ripple still works correctly as well. 

No, Pulses build process is entirely standard... All of the dependencies are listed on the `build.gradle` file. Unfortunately I don't have a clue what this could be, at this time.

**Comment by TChilderhose** [comment]
Hmm. Well I had some time this afternoon so I grabbed the repo and made a debug build with the latest and yeah it looks fine. So yeah, I'm stumped. 

Any issues running the debug version for awhile? or should I just stick with `v5.2.0`

Going to close the issue, but would you mind trying a clean build for next release?

Thanks!

**Comment by klinker24** [comment]
I'm not sure what you mean by "trying a clean build for the next release". All of my releases are done on CI. All of them are clean builds.

No, there aren't any issues running a debug version of the app

**Comment by TChilderhose** [comment]
Ah okay. Was meaning either clean project if you manually did it or have the "clean before checkout" type option enabled. I know it's disabled by default on most CI so wasn't sure if you had that enabled or not, but sounds like you do. Alright, disregard. Thanks anyways.
