### ISSUE TITLE
I can't login

### ISSUE THREAD

**Issue by linhtranle79** [klinker-apps/pulse-sms-issues#995]
*Please read my notes, then replace my notes to fill in this template with your own information and check the box to confirm you understand the request.*

## Confirm this Issue

- [x] This is something that I am looking to code myself and create a PR for, not a feature request for @klinker24 to code.
- [ ] This is a larger change that I am considering, which I would like feedback on, to discuss implementation details, or to confirm whether or not this is something that would be merged into the app.

If you are considering a small change/tweak or bug fix, feel free to just open the PR on the repo you are contributing to. Otherwise, let's talk here!

### Describe Your Request

Put in any request details you want to discuss here. If you have mockups, have considered any alternatives, or have any questions... Put them here! The more information, the easier time I will have understanding your request.

**Comment by linhtranle79** [comment]
I can't login with
app

**Comment by klinker24** [comment]
Please send me an email to troubleshoot account issues. This page is not for questions or troubleshooting, it is for detailed bug reports or feature requests.
