### ISSUE TITLE
Domain parked / renew now message on OSX Desktop and web app

### ISSUE THREAD

**Issue by apricot23** [klinker-apps/pulse-sms-issues#997]
*Please read my notes, then replace my notes to fill in this template with your own information and check the boxes to confirm you understand the report that you are filing.*

## Confirm this Issue

- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.

- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [X] I have verified that this is something that is reproducible.
- [X] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Device/Platform Information

**Device with issue:** Macbook Pro on OSX 10.15.4, Firefox Beta 77.0b9; PLUS Electron Desktop app
**Primary device:** Galaxy S7 on Oreo
**App version:** 5.3.1.2743

## Describe the Bug

`https://pulsesms.app/` loads a generic domain parked / "Renew now" page.

### Steps to Reproduce

This happens when I load the web app in Firefox or if I use the Desktop app on my Mac.

### Expected Behavior

My messages should be listed out to me but the page is broken.

**Comment by izaxone** [comment]
I am seeing this on Pulse SMS Desktop App as well. I just installed a fresh copy of the app on Linux from, and it shows the following message: 

```
pulsesms.app Renew Now 

Related Searches

This webpage was generated by the domain owner using Sedo Domain Parking. Disclaimer: Sedo maintains no relationship with third party advertisers. Reference to any specific service or trade mark is not controlled by Sedo nor does it constitute or imply its association, endorsement or recommendation.
```

Screenshot of the issue: https://imgur.com/NnXP1yF.png

**Comment by klinker24** [comment]
This has already been fixed.
