### ISSUE TITLE
Can't open web links to external browser

### ISSUE THREAD

**Issue by uudruid74** [klinker-apps/pulse-sms-issues#998]
## Confirm this Issue

- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [X] I have verified that this is something that is reproducible.
- [X] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Device/Platform Information

**Device with issue:** Ex: MacBook Pro on MacOS 10.12, running Chrome v54
OnePlus 7 Pro, latest stable OOS (Android 10)
**Primary device:** Ex: Pixel XL on Android 9
Above
**App version:** Ex: v4.1.5
5.3.2.2747
## Describe the Bug
I usually keep "use built in browser" turned on but the number of steps it takes to Chrome was killing me.  I generally hate ALL internal browsers - no reason to divide my history, passwords, etc between multiple apps, but I wanted the link previews.  

Once I turned off the checkbox, clicking on links doesn't open them!

### Steps to Reproduce

1. Settings, Browser
2. Turn off
3. Click a link

`... more steps`

### Expected Behavior

I expected Chrome to open.  Actually, it's running.  I expected a new tab to open within the running Chrome

**Comment by klinker24** [comment]
Unfortunately I am not able to replicate this issue. When I turn off the preference I click any link, it opens to Chrome, as expected.

If the preference is turned on, you can also long click the link to open it to the external browser.

**Comment by uudruid74** [comment]
OK. I did some more experimenting.  It looks like the issue is a lack of the http:// prefix.  See screenshot.

Also, when I press the link to get the menu, I get Open in Browser and Open Internally.  I want links to open in Chrome, my preferred Browser in Android Settings.  What is the "Browser" here?   There is no such app on my system.  This seems redundant.

Open internal gives me an option to open in browser which gives me an option to open in Chrome.  Holding and selecting Browser from the menu is one less step, but still too many.  A plain click does nothing, possibly because there is no http prefix?

![Screenshot_20200526-205555](https://user-images.githubusercontent.com/7726301/82968859-dcb3c800-9f93-11ea-9eeb-00868d23307d.png)

**Comment by klinker24** [comment]
Browser is a standard terms for any web browser, including Chrome. Chrome is a web browser. The app doesn't know, have to know, or care what web browser you are using. Opening to "browser" will open to your web browser: Chrome.

The internal browser says "open to chrome" even if the user doesn't have Chrome installed. Feel free to create a PR to change the wording, if it bothers you.

https://github.com/klinker41/article-android

I will explore if the http/https prefix is the issue. Thanks for the report.

**Comment by uudruid74** [comment]
No, what I'm saying is that it opens in some weird minimalistic browser that I've never seen before.  I don't know where it came from.  I have to open in the nameless browser and then use the menu in that browser to open in Chrome.

https://youtu.be/yLN8CgknsBQ

**Comment by klinker24** [comment]
That is a Chrome Custom tab.

**Comment by uudruid74** [comment]
OK, well it doesn't have a Share option.  This mess started because I'm doing something very simple - posting news I get via SMS to my Facebook.  The SMS URLs use an URL shortener that Facebook has blocked, so I have to open it before sharing.  With the built-in browser turned on I get the pretty preview but it tries to share the original URL.  I then Open In Browser only to get a Chrome Tab that doesn't have a Share option, then I have to open again.

With the internal browser turned off, I lose the previews, can't open with a tap and have to use a long press, then select from the menu, then I get a Chrome tab and have to open in Chrome to Share.

From the OS stock messenger, 1 tap gives me Copy and Open options, and Open gives me a real Chrome with a Share.  From Google Messenger, 1 tap and it opens in a real Chrome tab so I can Share it.  I still get my previews and I still get to text via my laptop with a web option.

Tell me why I'm being unreasonable to not want 3 extra steps to share an article?  I've been using Pulse for years, but I'm switching to Google Messenger because its just too many steps in this work flow and I want the computer to work FOR me, not AGAINST me.

**Comment by klinker24** [comment]
Then just turn off the internal browser and open directly to Chrome. I already said that I would explore if the lack of http/https prefixes caused your bug.

If previews are important to you, then you can go through the process of decoupling the option and submitting a pull request, as I already told you. The app is open source, customize it however you want. 

Thank you for the report on this bug. I will explore it further and post back if I have any additional feedback. Enjoy the rest of your day.
