### ISSUE TITLE
Decouple link preview from internal browser

### ISSUE THREAD

**Issue by uudruid74** [klinker-apps/pulse-sms-issues#999]
# Confirm this Issue

- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.
- [X] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Describe Your Request

I would love to see the web previews as-is, but still have Chrome open when that preview is clicked.

### Describe alternatives you've considered

Having these coupled may be easier to program but requires settling for extra steps in getting the link my chosen browser, or I suffer from no previews.  There should be a way to catch the click action upon the preview/link and open an external browser instead

**Comment by klinker24** [comment]
Sorry, this is not something that I have planned on my end. The goal of Pulse is not to have preferences to tweak every little behavior. 

If you are interested in this, it would fit well as an open source experiment, as described on my readme

https://github.com/klinker-apps/pulse-sms-android#open-source-experiments-settings-page
